ALTER TABLE movies ADD COLUMN new_id UUID NULL;
UPDATE movies SET new_id = CAST(LPAD(TO_HEX(id), 32, '0') AS UUID);
ALTER TABLE movies DROP COLUMN id;
ALTER TABLE movies RENAME COLUMN new_id TO id;
ALTER TABLE movies ALTER COLUMN id SET NOT NULL;